[environment]
python-version = "3.13"
root = ["./src"]

[rules]
all = "error"
unresolved-import = "ignore"

[src]
include = ["src", "tests"]

[terminal]
output-format = "concise"

[analysis]
replace-imports-with-any = [
    "pgvector.**",
]
